name: build for release
on:
  release:
    types: 
      - prereleased
      - released

jobs:
  build:
    name: build and upload artifacts to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Upload artifacts to release page
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/awesome-firmware.bin
