name: Install node

on:
  push:

jobs:
  install_node:
    name: Install node by specify version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ".node-version"
          cache: yarn
